### ISSUE TITLE
The 'class' attribute: as array or as string?

### ISSUE THREAD

**Issue by alexd73** [yannickoo/menu_link_attributes#60]
Hi! 
~~~I understand that you assign the value of the attribute 'class' for link as a string, but I cannot find where it in the code. :(~~~
I was looking for it because I added In my `THEME_preprocess_menu` this attributes as array and got this error `Error: [] operator not supported for strings` after enabling module `menu_link_attributes'

I used this code:
```   
$attrs = $item['url']->getOption('attributes');
// Error on this line and $attrs['class'] = "btn btn-primary text-light"; (I was set it on the menu option)
$attrs['class'][] = 'nav-link'; 
```
I'm not sure that I assign the attribute class correctly as an array, but stackoverflow says so :)

**Comment by alexd73** [comment]
I made a patch that changes all attributes, except for the target, to arrays.
```
diff --git a/menu_link_attributes.module b/menu_link_attributes.module
index e6c2b3d..568f0ea 100644
--- a/menu_link_attributes.module
+++ b/menu_link_attributes.module
@@ -122,9 +122,15 @@ function menu_link_attributes_menu_link_content_form_submit($form, FormStateInte
     return;
   }
 
-
   $menu_link_options = $menu_link->link->first()->options ?: [];
-  $menu_link_attributes = ['attributes' => $form_state->getValue('attributes')];
+  $menu_link_attributes = [];
+
+  foreach ($form_state->getValue('attributes') as $attribute_name => $value) {
+    if ($attribute_name == 'target') {
+      continue;
+    }
+    $menu_link_attributes['attributes'][$attribute_name] = explode(" ", $value);
+  }
 
   foreach ($menu_link_attributes['attributes'] as $attribute_name => $attribute_value) {
     $is_container_attribute = menu_link_attributes_is_container_attribute($attribute_name);
                                                                                                                            
 
```
[60_link_class_as_array.patch.txt](https://github.com/yannickoo/menu_link_attributes/files/2486268/60_link_class_as_array.patch.txt)

**Comment by tallytarik** [comment]
Tested, confirmed working. Thanks @alexd73!

In particular, `attributes['class']` needs to be an array in Drupal 8.

I encountered this error when using menu_link_attributes along with the link_trail_by_path module.

**Comment by jnettik** [comment]
I'm running into this issue too. Really, there's no reason to single out `target` because Drupal's `Attribute` class converts all arrays into strings when they render right? So all attributes can be safely formatted as an array.

https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Template!Attribute.php/class/Attribute/8.8.x

**Comment by jnettik** [comment]
Attached a patch against latest dev that addresses this by doing two things:

1. Before saving the attributes, it makes their values an array instead of a string.
2. Instead of replacing the options on a menu item entirely, we merge any existing attributes in with the new ones. That way we're not overriding any other classes getting set upstream from this module.

[60-attributes-as-array.patch.txt](https://github.com/yannickoo/menu_link_attributes/files/4696676/60-attributes-as-array.patch.txt)

**Comment by jnettik** [comment]
There was an issue with my earlier patch where I wasn't properly checking whether or not a saved menu item had attributes to get set. This new patch addresses that.

[60-attributes-as-array-2.patch.txt](https://github.com/yannickoo/menu_link_attributes/files/4737378/60-attributes-as-array-2.patch.txt)

**Comment by JPustkuchen** [comment]
Yep, should be an array value, not string!
See https://www.drupal.org/project/claro/issues/3109245 and please comment there.

**Comment by jcnventura** [comment]
As mentioned in https://github.com/yannickoo/menu_link_attributes/issues/60#issuecomment-634971246, there's no reason to single out target.

**Comment by jnettik** [comment]
I'm not actually sure where the best place to update this is anymore. The ticket on Claro is closed since the issue should be fixed here. I did run into a bug with my last patch. Here's an update that fixes that:

[60-attributes-as-array-3.patch.txt](https://github.com/yannickoo/menu_link_attributes/files/5895172/60-attributes-as-array-3.patch.txt)

**Comment by jcnventura** [comment]
Now that there are MRs in drupal.org, it doesn't make sense to keep these GitHub issues. Can you please also check https://www.drupal.org/project/menu_link_attributes/issues/3193364 ?

**Comment by JPustkuchen** [comment]
Hi all,
this important issue still exists, has no corresponding issue on Drupal.org yet but this is being closed with all information?

Why?

We can't simply close such a bug and wait until someone reports it again. There was no new release for the module yet fixing this.

**Comment by yannickoo** [comment]
_This issue has been moved to Drupal.org – [#3199777](https://www.drupal.org/project/menu_link_attributes/issues/3199777)_
