### ISSUE TITLE
Attributes do not render when menu item is expandable

### ISSUE THREAD

**Issue by ultimike** [yannickoo/menu_link_attributes#9]
I have a scenario where menu attributes added to menu items do not render.
1. Using Bootstrap as the base theme.  
2. Menu is a hierarchy.  
3. Attributes are added to a top-level menu item that has child menu items.

For example:
- Menu 1  
- Menu 2 
  - Menu 2.1  
  - Menu 2.2  
- Menu 3

When I enable this module, and add an attribute to "Menu 2.1", and show it as expanded, the attribute does not display. 

But, if I add an attribute to "Menu 3", the attribute displays properly. 

It appears that this is a conflict between this module and Bootstrap...

-mike

**Comment by yannickoo** [comment]
Hey @ultimike, this issue has been fixed in 48b4dc962f0cd37d179bd93bf86dc04ddbf95668 :)

**Comment by atif-kht** [comment]
Hi I can confirm that this issue still exists in Drupal8 with bootstrap sub-theme and this module. Please try to figure out the way to resolve this issue. 

Bundle of thanks

**Comment by atif-kht** [comment]
@yannickoo Can you please confirm that this is resolved? I am still facing the issue on my site and not able to get attributes on parent items.

**Comment by atif-kht** [comment]
I am not able to apply attributes on items which are expanded and having children

**Comment by hatuhay** [comment]
I can confirm the issue, does not work on bootstrap_barrio theme neither, using standard bootstrap menu marckup

**Comment by mikemichalak** [comment]
This also occurs for me as well.  Using a custom them but with bootstrap.

**Comment by nanobyt3** [comment]
If anyone is still facing this issue of compatibility between bootstarp theme and menu_link_attributes module, please see my post here: https://www.drupal.org/project/bootstrap/issues/2706595#comment-12482335

**Comment by jigarius** [comment]
I'm facing a similar problem, but with `classy`.
